echo Removing node_modules dir...
rm -r ./commercial/ospman/node_modules
echo Removing webpack* files...
rm ./commercial/ospman/webpack*
echo Removing package* files...
rm ./commercial/ospman/package*