/*
 *  Copyright 2010-2018 Neotropic SAS <contact@neotropic.co>.
 *
 *  Licensed under the EPL License, Version 1.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.eclipse.org/legal/epl-v10.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.kuwaiba.web.modules.servmanager.dashboard;

import com.vaadin.icons.VaadinIcons;
import com.vaadin.server.ExternalResource;
import com.vaadin.shared.ui.ContentMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.security.SecureRandom;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.List;
import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonReader;
import javax.json.JsonValue;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.X509TrustManager;
import org.kuwaiba.apis.persistence.exceptions.InvalidArgumentException;
import org.kuwaiba.apis.web.gui.dashboards.AbstractDashboardWidget;
import org.kuwaiba.apis.web.gui.notifications.Notifications;
import org.kuwaiba.beans.WebserviceBean;
import org.kuwaiba.interfaces.ws.toserialize.business.RemoteObjectLight;

/**
 * This widget embeds an image generated by a Zabbix graph. This widget assumes that the graph is named after the selected service .
 * The graph name must have the following structure: ANY_STRING:SERVICE_NAME or simply SERVICE_NAME
 * @author Charles Edward Bedon Cortazar <charles.bedon@kuwaiba.org>
 */
public class ZabbixGraphDashboardWidget extends AbstractDashboardWidget {
    /**
     * URL to be used to make the API requests
     */
    private final static String DEFAULT_ZABBIX_API_ENDPOINT_URL = "http://localhost/zabbix/api_jsonrpc.php";
    /**
     * Default Zabbix user if none specified
     */
    private final static String DEFAULT_ZABBIX_USER = "Admin";
    /**
     * Default Zabbix password if none specified
     */
    private final static String DEFAULT_ZABBIX_PASSWORD = "zabbix";
    /**
     * Reference to the selected service
     */
    private RemoteObjectLight service;
    /**
    * Reference to the backend bean
    */
    private WebserviceBean wsBean;
    /*
    * The graphs currently associated to the selected service
    */
    private List<ZabbixGraph> zabbixGraphs;
    /**
     * Variable indicating the index in the currentGraphs array of the current graph on display.
     */
    private int currentGraphIndex = 0;
    /**
     * A panel containing the current graph on display
     */
    private Panel pnlZabbixGraphs;
    
    public ZabbixGraphDashboardWidget(RemoteObjectLight service, WebserviceBean wsBean) {
        super(String.format("Zabbix Graphs for %s", service));
        addStyleName("dashboard");
        this.service = service;
        this.wsBean = wsBean;
        this.createContent();
    }
   
    @Override
    public void createContent() { 
        addComponents(new Label(String.format("<h2>%s</h2>", service), ContentMode.HTML));
        
        try {
            
//            try {
//                wsB
//            } catch (ServerSideException ex) {
//            }
            
            //Login
            String authResponse = createHttpPostRequestForTextResponse("http://localhost/zabbix/api_jsonrpc.php", "{\n" +
            "    \"jsonrpc\": \"2.0\",\n" +
            "    \"method\": \"user.login\",\n" +
            "    \"params\": {\n" +
            "        \"user\": \"Admin\",\n" +
            "        \"password\": \"zabbix\"\n" +
            "    },\n" +
            "    \"id\": 1,\n" +
            "    \"auth\": null\n" +
            "}");
            
            JsonReader authReader = Json.createReader(new StringReader(authResponse));
            JsonObject authObject = authReader.readObject();
            
            if (!authObject.containsKey("result")) {
                Notifications.showError(String.format("The Zabbix server returned an error code: %s", authObject.containsKey("error") ? authObject.getString("error") : "No further details"));
                return;
            }
            
            String authKey = authObject.getString("result");
            
            
            String graphResponse = createHttpPostRequestForTextResponse("http://localhost/zabbix/api_jsonrpc.php", "{\n" +
            "    \"jsonrpc\": \"2.0\",\n" +
            "    \"method\": \"graph.get\",\n" +
            "    \"params\": {\n" +
            "        \"output\": \"extend\",\n" +
            "        \"expandName\": true \n" + //This is very important. If not included, Zabbix will return the name of the template (which is composed by placeholders) instead of the actual name of the graph
            "    },\n" +
            "    \"auth\": \"" + authKey + "\",\n" +
            "    \"id\": 1\n" +
            "}");
            
            JsonReader graphReader = Json.createReader(new StringReader(graphResponse));
            JsonObject graphObject = graphReader.readObject();
            
            JsonArray jsonGraphs = graphObject.getJsonArray("result");
            zabbixGraphs = new ArrayList<>();
            
            for (JsonValue jsonGraph : jsonGraphs) {
                String[] graphNameTokens = ((JsonObject)jsonGraph).getString("name").split(":");
                
                //if (service.getName().equals(graphNameTokens[graphNameTokens.length - 1]))
                //System.out.println(String.format("graphsMap.put(\"%s\", %s)", ((JsonObject)jsonGraph).getString("name"), ((JsonObject)jsonGraph).getString("graphid")));
                if (((JsonObject)jsonGraph).getString("name").contains(service.getName()))
                    zabbixGraphs.add(new ZabbixGraph(((JsonObject)jsonGraph).getString("graphid"), ((JsonObject)jsonGraph).getString("name")));
            }
            if (zabbixGraphs.isEmpty())
                addComponent(new Label("This service does not have Zabbix graphs associated to it. If this is not the case, please check your naming conventions or contact an administrator"));
            else {
                
                pnlZabbixGraphs = new Panel();
                pnlZabbixGraphs.setSizeUndefined();
                
                HorizontalLayout lytCaroussel = new HorizontalLayout();
                lytCaroussel.setSizeFull();
                
                Button btnPreviousGraph = new Button(VaadinIcons.ARROW_LEFT);
                btnPreviousGraph.setEnabled(false);
                btnPreviousGraph.addClickListener((event) -> {
                    if (currentGraphIndex < 0) {
                        currentGraphIndex = 0;
                        return;
                    }
                    
                    if (currentGraphIndex == 0) 
                        btnPreviousGraph.setEnabled(false);
                    else
                        currentGraphIndex--;
                    
                    updateZabbixGraph();
                });
                
                Button btnNextGraph = new Button(VaadinIcons.ARROW_RIGHT);
                btnNextGraph.setEnabled(zabbixGraphs.size() > 1);
                
                btnNextGraph.addClickListener((event) -> {
                    
                    if (currentGraphIndex == zabbixGraphs.size() - 1)
                        currentGraphIndex = 0;
                    else 
                        currentGraphIndex++;
                    
                    btnPreviousGraph.setEnabled(currentGraphIndex > 0);
                    
                    updateZabbixGraph();
                });
                
                updateZabbixGraph();
                lytCaroussel.addComponents(btnPreviousGraph, pnlZabbixGraphs, btnNextGraph);
                lytCaroussel.setExpandRatio(btnNextGraph, 2);
                lytCaroussel.setExpandRatio(pnlZabbixGraphs, 6);
                lytCaroussel.setExpandRatio(btnPreviousGraph, 2);

                lytCaroussel.setComponentAlignment(pnlZabbixGraphs, Alignment.MIDDLE_CENTER);
                lytCaroussel.setComponentAlignment(btnPreviousGraph, Alignment.MIDDLE_LEFT);
                lytCaroussel.setComponentAlignment(btnNextGraph, Alignment.MIDDLE_RIGHT);
                
                pnlZabbixGraphs.addClickListener((event) -> {
                    Window wdwGraphs = new Window(zabbixGraphs.get(currentGraphIndex).toString());
                    
                    VerticalLayout lytGraph = new VerticalLayout();
                    lytGraph.setSizeUndefined();
                    
                    Panel pnlZabbixGraph = new Panel(new Image(wdwGraphs.getCaption(), 
                            new ExternalResource("http://localhost/zabbix/chart2.php?graphid=" + zabbixGraphs.get(currentGraphIndex).id + 
                                    "&period=3600&isNow=1&profileIdx=web.graphs&profileIdx2=798&width=1194")));
                    
                    lytGraph.addComponents(pnlZabbixGraph);
                    
                    wdwGraphs.setModal(true);
                    wdwGraphs.setHeight(80, Unit.PERCENTAGE);
                    wdwGraphs.setWidth(100, Unit.PERCENTAGE);
                    wdwGraphs.setContent(lytGraph);
                    
                    UI.getCurrent().addWindow(wdwGraphs);
                });
                
                addComponent(lytCaroussel);
                
            }
            //Logout
            createHttpPostRequestForTextResponse("http://localhost/zabbix/api_jsonrpc.php", "{\n" +
                    "    \"jsonrpc\": \"2.0\",\n" +
                    "    \"method\": \"user.logout\",\n" +
                    "    \"params\": [],\n" +
                    "    \"id\": 1,\n" +
                    "    \"auth\": \"" + authKey +  " \"\n" +
                    "}");
            
            
        } catch (InvalidArgumentException ex) {
            Notifications.showError(ex.getLocalizedMessage());
        }
    }
    
    /**
     * Replaces the image currently on display at the Zabbix graphs panel with the current seleted graph
     */
    private void updateZabbixGraph() {
        Image newGraph = new Image("", 
                        new ExternalResource("http://localhost/zabbix/chart2.php?graphid=" + zabbixGraphs.get(currentGraphIndex).id + 
                                    "&period=3600&isNow=1&profileIdx=web.graphs&profileIdx2=798&width=1194"));
        newGraph.setStyleName("theater-layout-screen-image");
        pnlZabbixGraphs.setCaption(zabbixGraphs.get(currentGraphIndex).toString());
        pnlZabbixGraphs.setContent(newGraph);
    }
    
    /**
     * Creates an HTTP requests and expects a text-based response
     * @param url Target URL
     * @return The response as a text
     * @throws InvalidArgumentException If there's an error while contacting the server 
     */
    private String createHttpPostRequestForTextResponse(String url, String content) throws InvalidArgumentException {
        try {
            trustEveryone();
            HttpURLConnection connection = (HttpURLConnection)new URL(url).openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("User-Agent", "Mozilla/5.0");
            connection.setRequestProperty("Content-Type", "application/json-rpc");
            connection.setDoOutput(true);
            
            
            OutputStreamWriter outputStreamWriter = new OutputStreamWriter(connection.getOutputStream());
            outputStreamWriter.write(content);
            outputStreamWriter.flush();
            
            int responseCode = connection.getResponseCode();

            if (responseCode == HttpURLConnection.HTTP_OK) { //HTTP OK
                try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
                    String inputLine;
                    StringBuilder response = new StringBuilder();

                    while ((inputLine = in.readLine()) != null)
                        response.append(inputLine);
                    
                    return response.toString();
                }
            } else 
                throw new InvalidArgumentException(String.format("The Zabbix server returned an error code %s. Contact your administrator", responseCode));
        } catch (IOException ex) {
            throw new InvalidArgumentException(String.format("An unexpected error occurred while loading Zabbix graphics: %s", ex.getLocalizedMessage()));
        }
    }
    
    
private void trustEveryone() { 
    try { 
            HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier(){ 
                    public boolean verify(String hostname, SSLSession session) { 
                            return true; 
                    }}); 
            SSLContext context = SSLContext.getInstance("TLS"); 
            context.init(null, new X509TrustManager[]{new X509TrustManager(){ 
                    public void checkClientTrusted(X509Certificate[] chain, 
                                    String authType) throws CertificateException {} 
                    public void checkServerTrusted(X509Certificate[] chain, 
                                    String authType) throws CertificateException {} 
                    public X509Certificate[] getAcceptedIssuers() { 
                            return new X509Certificate[0]; 
                    }}}, new SecureRandom()); 
            HttpsURLConnection.setDefaultSSLSocketFactory( 
                            context.getSocketFactory()); 
    } catch (Exception e) { // should never happen 
            e.printStackTrace(); 
    } 
} 
    

    /**
     * A simple POJO that represents a Zabbix graph and that can be used in lists and combo boxes
     */
    private class ZabbixGraph {
        /**
         *  Graph id
         */
        private String id;
        /**
         * Graph name
         */
        private String name;

        public ZabbixGraph(String id, String name) {
            this.id = id;
            this.name = name;
        }
        
        @Override
        public String toString(){
            return name;
        }
    }
}