/*
 *  Copyright 2010 zim.
 * 
 *   Licensed under the EPL License, Version 1.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *        http://www.eclipse.org/legal/epl-v10.html
 * 
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 * 
 */

package org.inventory.core.usermanager;

import java.awt.BorderLayout;
import java.util.logging.Logger;
import org.inventory.core.services.interfaces.NotificationUtil;
import org.inventory.core.usermanager.actions.AddUser;
import org.inventory.core.usermanager.actions.UpdateList;
import org.openide.explorer.ExplorerManager;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.explorer.ExplorerManager.Provider;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.TableView;
import org.openide.util.Lookup;

/**
 * This component show the available options for users and groups management
 */
@ConvertAsProperties(
    dtd="-//org.inventory.core.usermanager//UserManager//EN",
    autostore=false
)
public final class UserManagerTopComponent extends TopComponent
    implements Provider{

    private static UserManagerTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/inventory/core/usermanager/res/icon.png";

    private static final String PREFERRED_ID = "UserManagerTopComponent";

    private ExplorerManager em = new ExplorerManager();
    private TableView tblUsers;
    private TableView tblGroups;
    private UserManagerService ums;
    private NotificationUtil nu = null;

    public UserManagerTopComponent() {
        initComponents();
        initCustomComponents();
        setName(NbBundle.getMessage(UserManagerTopComponent.class, "CTL_UserManagerTopComponent"));
        setToolTipText(NbBundle.getMessage(UserManagerTopComponent.class, "HINT_UserManagerTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        
    }

    public void initCustomComponents(){
        this.ums = new UserManagerService(this);
        ums.populateUsersList();

        //this.tblGroups = new TableView();
        
        pnlUsers.add(tblUsers,BorderLayout.CENTER);
       // pnlUsers.add(tblGroups);
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        btnAddUser.addActionListener(new AddUser(em.getRootContext(),ums));
        btnRefresh.addActionListener(new UpdateList(pnlTabbedMain, ums));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barMain = new javax.swing.JToolBar();
        btnAddUser = new javax.swing.JButton();
        btnAddGroup = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        pnlTabbedMain = new javax.swing.JTabbedPane();
        pnlTabUsers = new javax.swing.JPanel();
        pnlScrollUsers = new javax.swing.JScrollPane();
        pnlUsers = new javax.swing.JPanel();
        pnlTabGroups = new javax.swing.JPanel();
        pnlScrollGroups = new javax.swing.JScrollPane();
        pnlGroups = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        barMain.setRollover(true);

        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inventory/core/usermanager/res/addUser.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnAddUser, org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnAddUser.text")); // NOI18N
        btnAddUser.setToolTipText(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnAddUser.toolTipText")); // NOI18N
        btnAddUser.setFocusable(false);
        btnAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barMain.add(btnAddUser);

        btnAddGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inventory/core/usermanager/res/addGroup.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnAddGroup, org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnAddGroup.text")); // NOI18N
        btnAddGroup.setToolTipText(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnAddGroup.toolTipText")); // NOI18N
        btnAddGroup.setFocusable(false);
        btnAddGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barMain.add(btnAddGroup);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inventory/core/usermanager/res/edit.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnEdit, org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnEdit.text")); // NOI18N
        btnEdit.setToolTipText(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnEdit.toolTipText")); // NOI18N
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barMain.add(btnEdit);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inventory/core/usermanager/res/delete.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnDelete, org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnDelete.text")); // NOI18N
        btnDelete.setToolTipText(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnDelete.toolTipText")); // NOI18N
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barMain.add(btnDelete);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inventory/core/usermanager/res/refresh.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnRefresh, org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnRefresh.text")); // NOI18N
        btnRefresh.setToolTipText(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.btnRefresh.toolTipText")); // NOI18N
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barMain.add(btnRefresh);

        txtSearch.setText(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.txtSearch.text")); // NOI18N
        barMain.add(txtSearch);

        add(barMain, java.awt.BorderLayout.PAGE_START);

        pnlTabUsers.setLayout(new java.awt.BorderLayout());

        pnlUsers.setLayout(new java.awt.BorderLayout());
        pnlScrollUsers.setViewportView(pnlUsers);

        pnlTabUsers.add(pnlScrollUsers, java.awt.BorderLayout.CENTER);

        pnlTabbedMain.addTab(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.pnlTabUsers.TabConstraints.tabTitle"), pnlTabUsers); // NOI18N

        pnlTabGroups.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlGroupsLayout = new javax.swing.GroupLayout(pnlGroups);
        pnlGroups.setLayout(pnlGroupsLayout);
        pnlGroupsLayout.setHorizontalGroup(
            pnlGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        pnlGroupsLayout.setVerticalGroup(
            pnlGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        pnlScrollGroups.setViewportView(pnlGroups);

        pnlTabGroups.add(pnlScrollGroups, java.awt.BorderLayout.CENTER);

        pnlTabbedMain.addTab(org.openide.util.NbBundle.getMessage(UserManagerTopComponent.class, "UserManagerTopComponent.pnlTabGroups.TabConstraints.tabTitle"), pnlTabGroups); // NOI18N

        add(pnlTabbedMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barMain;
    private javax.swing.JButton btnAddGroup;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel pnlGroups;
    private javax.swing.JScrollPane pnlScrollGroups;
    private javax.swing.JScrollPane pnlScrollUsers;
    private javax.swing.JPanel pnlTabGroups;
    private javax.swing.JPanel pnlTabUsers;
    private javax.swing.JTabbedPane pnlTabbedMain;
    private javax.swing.JPanel pnlUsers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized UserManagerTopComponent getDefault() {
        if (instance == null) {
            instance = new UserManagerTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the UserManagerTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized UserManagerTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(UserManagerTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof UserManagerTopComponent) {
            return (UserManagerTopComponent)win;
        }
        Logger.getLogger(UserManagerTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        //ToolbarPool.getDefault().findToolbar("UserManager").setVisible(true);
    }

    @Override
    public void componentClosed() {
        //ToolbarPool.getDefault().findToolbar("UserManager").setVisible(false);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }
    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    public TableView getTblGroups() {
        return tblGroups;
    }

    public TableView getTblUsers() {
        return tblUsers;
    }

    public NotificationUtil getNotifier(){
        if(this.nu == null)
            this.nu = Lookup.getDefault().lookup(NotificationUtil.class);
        return this.nu;
    }

    void setTblUsers(TableView tableView) {
        this.tblUsers = tableView;
    }
}
