/**
 *  Copyright 2010-2017 Neotropic SAS <contact@neotropic.co>.
 *
 *  Licensed under the EPL License, Version 1.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.eclipse.org/legal/epl-v10.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.inventory.models.physicalconnections.wizards;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.inventory.communications.CommunicationsStub;
import org.inventory.communications.core.LocalClassMetadataLight;
import org.inventory.communications.core.LocalObjectLight;
import org.inventory.communications.util.Constants;

/**
 * The panel of the first step of the New Container wizard
 * @author Charles Edward Bedon Cortazar <charles.bedon@kuwaiba.org>
 */
public class NewContainerVisualPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form NewContainerVisualPanel1
     */
    public NewContainerVisualPanel1() {
        initComponents();
        List<LocalClassMetadataLight> containerClasses = CommunicationsStub.getInstance().
                getLightSubclasses(Constants.CLASS_GENERICPHYSICALCONTAINER, false, false);
        
        cmbContainerClass.setModel(containerClasses == null ? new DefaultComboBoxModel() : new DefaultComboBoxModel(containerClasses.toArray()));
        cmbContainerClass.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    LocalClassMetadataLight selectedClass = (LocalClassMetadataLight)cmbContainerClass.getSelectedItem();
                    if (selectedClass != null) { //Should not happen, though
                        List<LocalObjectLight> containerTemplates = CommunicationsStub.getInstance().getTemplatesForClass(selectedClass.getClassName(), false);
                        if (containerTemplates != null) {
                            cmbContainerTemplates.setModel(new DefaultComboBoxModel(containerTemplates.toArray(new LocalObjectLight[0])));
                            cmbContainerTemplates.setEnabled(true);
                            return;
                        }
                    } 
                    cmbContainerTemplates.setModel(new DefaultComboBoxModel());
                }
            }
        });
        if (cmbContainerClass.getItemCount() > 0) //So that the item selection svent is triggered
            cmbContainerClass.setSelectedIndex(0);
    }
    
    public LocalClassMetadataLight getContainerClass() {
        return (LocalClassMetadataLight)cmbContainerClass.getSelectedItem();
    }
    
    public LocalClassMetadataLight getContainerType() {
        return (LocalClassMetadataLight)cmbContainerTemplates.getSelectedItem();
    }
    
    @Override
    public String getName() {
        return "Container class and type";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContainerClass = new javax.swing.JLabel();
        cmbContainerClass = new javax.swing.JComboBox();
        lblCOntainerTemplate = new javax.swing.JLabel();
        cmbContainerTemplates = new javax.swing.JComboBox();
        lblContainerName = new javax.swing.JLabel();
        txtContainerName = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(lblContainerClass, org.openide.util.NbBundle.getMessage(NewContainerVisualPanel1.class, "NewContainerVisualPanel1.lblContainerClass.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCOntainerTemplate, org.openide.util.NbBundle.getMessage(NewContainerVisualPanel1.class, "NewContainerVisualPanel1.lblCOntainerTemplate.text")); // NOI18N

        cmbContainerTemplates.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(lblContainerName, org.openide.util.NbBundle.getMessage(NewContainerVisualPanel1.class, "NewContainerVisualPanel1.lblContainerName.text")); // NOI18N

        txtContainerName.setText(org.openide.util.NbBundle.getMessage(NewContainerVisualPanel1.class, "NewContainerVisualPanel1.txtContainerName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContainerClass)
                            .addComponent(lblCOntainerTemplate))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbContainerClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbContainerTemplates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContainerName)
                        .addGap(44, 44, 44)
                        .addComponent(txtContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerName)
                    .addComponent(txtContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerClass)
                    .addComponent(cmbContainerClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCOntainerTemplate)
                    .addComponent(cmbContainerTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbContainerClass;
    private javax.swing.JComboBox cmbContainerTemplates;
    private javax.swing.JLabel lblCOntainerTemplate;
    private javax.swing.JLabel lblContainerClass;
    private javax.swing.JLabel lblContainerName;
    private javax.swing.JTextField txtContainerName;
    // End of variables declaration//GEN-END:variables
}
